-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2024.2 (win64) Build 5239630 Fri Nov 08 22:35:27 MST 2024
-- Date        : Sun Mar 30 17:29:18 2025
-- Host        : Diogenes_Urn running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode funcsim
--               c:/Dev/masters_project/fp_gpu/fp_gpu.gen/sources_1/bd/fp_gpu/ip/fp_gpu_axi_interconnect_0_0/fp_gpu_axi_interconnect_0_0_sim_netlist.vhdl
-- Design      : fp_gpu_axi_interconnect_0_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity fp_gpu_axi_interconnect_0_0 is
  port (
    s_axi_hpr_arvalid : in STD_LOGIC;
    s_axi_hpr_arready : out STD_LOGIC;
    s_axi_hpr_araddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_hpr_arburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_hpr_arsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_hpr_arlen : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_hpr_rvalid : out STD_LOGIC;
    s_axi_hpr_rready : in STD_LOGIC;
    s_axi_hpr_rdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_hpr_rlast : out STD_LOGIC;
    s_axi_hpw_awvalid : in STD_LOGIC;
    s_axi_hpw_awready : out STD_LOGIC;
    s_axi_hpw_awaddr : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_hpw_awburst : in STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_hpw_awsize : in STD_LOGIC_VECTOR ( 2 downto 0 );
    s_axi_hpw_awlen : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_hpw_wvalid : in STD_LOGIC;
    s_axi_hpw_wready : out STD_LOGIC;
    s_axi_hpw_wdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_hpw_wstrb : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_hpw_wlast : in STD_LOGIC;
    s_axi_hpw_bvalid : out STD_LOGIC;
    s_axi_hpw_bready : in STD_LOGIC;
    m_axi_hp_arvalid : out STD_LOGIC;
    m_axi_hp_arready : in STD_LOGIC;
    m_axi_hp_araddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_hp_arburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_hp_arsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_hp_arlen : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_hp_rvalid : in STD_LOGIC;
    m_axi_hp_rready : out STD_LOGIC;
    m_axi_hp_rdata : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_hp_rlast : in STD_LOGIC;
    m_axi_hp_awvalid : out STD_LOGIC;
    m_axi_hp_awready : in STD_LOGIC;
    m_axi_hp_awaddr : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_hp_awburst : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_hp_awsize : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_hp_awlen : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_hp_wvalid : out STD_LOGIC;
    m_axi_hp_wready : in STD_LOGIC;
    m_axi_hp_wdata : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_hp_wstrb : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_hp_wlast : out STD_LOGIC;
    m_axi_hp_bvalid : in STD_LOGIC;
    m_axi_hp_bready : out STD_LOGIC
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of fp_gpu_axi_interconnect_0_0 : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of fp_gpu_axi_interconnect_0_0 : entity is "fp_gpu_axi_interconnect_0_0,axi_interconnect,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of fp_gpu_axi_interconnect_0_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of fp_gpu_axi_interconnect_0_0 : entity is "module_ref";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of fp_gpu_axi_interconnect_0_0 : entity is "axi_interconnect,Vivado 2024.2";
end fp_gpu_axi_interconnect_0_0;

architecture STRUCTURE of fp_gpu_axi_interconnect_0_0 is
  signal \^m_axi_hp_arready\ : STD_LOGIC;
  signal \^m_axi_hp_awready\ : STD_LOGIC;
  signal \^m_axi_hp_bvalid\ : STD_LOGIC;
  signal \^m_axi_hp_rdata\ : STD_LOGIC_VECTOR ( 31 downto 0 );
  signal \^m_axi_hp_rlast\ : STD_LOGIC;
  signal \^m_axi_hp_rvalid\ : STD_LOGIC;
  signal \^m_axi_hp_wready\ : STD_LOGIC;
  signal \^s_axi_hpr_araddr\ : STD_LOGIC_VECTOR ( 31 downto 0 );
  signal \^s_axi_hpr_arburst\ : STD_LOGIC_VECTOR ( 1 downto 0 );
  signal \^s_axi_hpr_arlen\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^s_axi_hpr_arsize\ : STD_LOGIC_VECTOR ( 2 downto 0 );
  signal \^s_axi_hpr_arvalid\ : STD_LOGIC;
  signal \^s_axi_hpr_rready\ : STD_LOGIC;
  signal \^s_axi_hpw_awaddr\ : STD_LOGIC_VECTOR ( 31 downto 0 );
  signal \^s_axi_hpw_awburst\ : STD_LOGIC_VECTOR ( 1 downto 0 );
  signal \^s_axi_hpw_awlen\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^s_axi_hpw_awsize\ : STD_LOGIC_VECTOR ( 2 downto 0 );
  signal \^s_axi_hpw_awvalid\ : STD_LOGIC;
  signal \^s_axi_hpw_bready\ : STD_LOGIC;
  signal \^s_axi_hpw_wdata\ : STD_LOGIC_VECTOR ( 31 downto 0 );
  signal \^s_axi_hpw_wlast\ : STD_LOGIC;
  signal \^s_axi_hpw_wstrb\ : STD_LOGIC_VECTOR ( 3 downto 0 );
  signal \^s_axi_hpw_wvalid\ : STD_LOGIC;
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of m_axi_hp_arready : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp ARREADY";
  attribute X_INTERFACE_INFO of m_axi_hp_arvalid : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp ARVALID";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of m_axi_hp_arvalid : signal is "master";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of m_axi_hp_arvalid : signal is "XIL_INTERFACENAME m_axi_hp, DATA_WIDTH 32, PROTOCOL AXI3, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_WRITE, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 0, HAS_RRESP 0, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_hp_awready : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp AWREADY";
  attribute X_INTERFACE_INFO of m_axi_hp_awvalid : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp AWVALID";
  attribute X_INTERFACE_INFO of m_axi_hp_bready : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp BREADY";
  attribute X_INTERFACE_INFO of m_axi_hp_bvalid : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp BVALID";
  attribute X_INTERFACE_INFO of m_axi_hp_rlast : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp RLAST";
  attribute X_INTERFACE_INFO of m_axi_hp_rready : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp RREADY";
  attribute X_INTERFACE_INFO of m_axi_hp_rvalid : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp RVALID";
  attribute X_INTERFACE_INFO of m_axi_hp_wlast : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp WLAST";
  attribute X_INTERFACE_INFO of m_axi_hp_wready : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp WREADY";
  attribute X_INTERFACE_INFO of m_axi_hp_wvalid : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp WVALID";
  attribute X_INTERFACE_INFO of s_axi_hpr_arready : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpr ARREADY";
  attribute X_INTERFACE_INFO of s_axi_hpr_arvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpr ARVALID";
  attribute X_INTERFACE_MODE of s_axi_hpr_arvalid : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_hpr_arvalid : signal is "XIL_INTERFACENAME s_axi_hpr, DATA_WIDTH 32, PROTOCOL AXI3, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE READ_ONLY, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 0, HAS_BRESP 0, HAS_RRESP 0, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_hpr_rlast : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpr RLAST";
  attribute X_INTERFACE_INFO of s_axi_hpr_rready : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpr RREADY";
  attribute X_INTERFACE_INFO of s_axi_hpr_rvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpr RVALID";
  attribute X_INTERFACE_INFO of s_axi_hpw_awready : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw AWREADY";
  attribute X_INTERFACE_INFO of s_axi_hpw_awvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw AWVALID";
  attribute X_INTERFACE_MODE of s_axi_hpw_awvalid : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_hpw_awvalid : signal is "XIL_INTERFACENAME s_axi_hpw, DATA_WIDTH 32, PROTOCOL AXI3, FREQ_HZ 100000000, ID_WIDTH 0, ADDR_WIDTH 32, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 1, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 0, HAS_RRESP 0, SUPPORTS_NARROW_BURST 1, NUM_READ_OUTSTANDING 2, NUM_WRITE_OUTSTANDING 2, MAX_BURST_LENGTH 16, PHASE 0.0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_hpw_bready : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw BREADY";
  attribute X_INTERFACE_INFO of s_axi_hpw_bvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw BVALID";
  attribute X_INTERFACE_INFO of s_axi_hpw_wlast : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw WLAST";
  attribute X_INTERFACE_INFO of s_axi_hpw_wready : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw WREADY";
  attribute X_INTERFACE_INFO of s_axi_hpw_wvalid : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw WVALID";
  attribute X_INTERFACE_INFO of m_axi_hp_araddr : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp ARADDR";
  attribute X_INTERFACE_INFO of m_axi_hp_arburst : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp ARBURST";
  attribute X_INTERFACE_INFO of m_axi_hp_arlen : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp ARLEN";
  attribute X_INTERFACE_INFO of m_axi_hp_arsize : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_hp_awaddr : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp AWADDR";
  attribute X_INTERFACE_INFO of m_axi_hp_awburst : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp AWBURST";
  attribute X_INTERFACE_INFO of m_axi_hp_awlen : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp AWLEN";
  attribute X_INTERFACE_INFO of m_axi_hp_awsize : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_hp_rdata : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp RDATA";
  attribute X_INTERFACE_INFO of m_axi_hp_wdata : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp WDATA";
  attribute X_INTERFACE_INFO of m_axi_hp_wstrb : signal is "xilinx.com:interface:aximm:1.0 m_axi_hp WSTRB";
  attribute X_INTERFACE_INFO of s_axi_hpr_araddr : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpr ARADDR";
  attribute X_INTERFACE_INFO of s_axi_hpr_arburst : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpr ARBURST";
  attribute X_INTERFACE_INFO of s_axi_hpr_arlen : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpr ARLEN";
  attribute X_INTERFACE_INFO of s_axi_hpr_arsize : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpr ARSIZE";
  attribute X_INTERFACE_INFO of s_axi_hpr_rdata : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpr RDATA";
  attribute X_INTERFACE_INFO of s_axi_hpw_awaddr : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw AWADDR";
  attribute X_INTERFACE_INFO of s_axi_hpw_awburst : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw AWBURST";
  attribute X_INTERFACE_INFO of s_axi_hpw_awlen : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw AWLEN";
  attribute X_INTERFACE_INFO of s_axi_hpw_awsize : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw AWSIZE";
  attribute X_INTERFACE_INFO of s_axi_hpw_wdata : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw WDATA";
  attribute X_INTERFACE_INFO of s_axi_hpw_wstrb : signal is "xilinx.com:interface:aximm:1.0 s_axi_hpw WSTRB";
begin
  \^m_axi_hp_arready\ <= m_axi_hp_arready;
  \^m_axi_hp_awready\ <= m_axi_hp_awready;
  \^m_axi_hp_bvalid\ <= m_axi_hp_bvalid;
  \^m_axi_hp_rdata\(31 downto 0) <= m_axi_hp_rdata(31 downto 0);
  \^m_axi_hp_rlast\ <= m_axi_hp_rlast;
  \^m_axi_hp_rvalid\ <= m_axi_hp_rvalid;
  \^m_axi_hp_wready\ <= m_axi_hp_wready;
  \^s_axi_hpr_araddr\(31 downto 0) <= s_axi_hpr_araddr(31 downto 0);
  \^s_axi_hpr_arburst\(1 downto 0) <= s_axi_hpr_arburst(1 downto 0);
  \^s_axi_hpr_arlen\(3 downto 0) <= s_axi_hpr_arlen(3 downto 0);
  \^s_axi_hpr_arsize\(2 downto 0) <= s_axi_hpr_arsize(2 downto 0);
  \^s_axi_hpr_arvalid\ <= s_axi_hpr_arvalid;
  \^s_axi_hpr_rready\ <= s_axi_hpr_rready;
  \^s_axi_hpw_awaddr\(31 downto 0) <= s_axi_hpw_awaddr(31 downto 0);
  \^s_axi_hpw_awburst\(1 downto 0) <= s_axi_hpw_awburst(1 downto 0);
  \^s_axi_hpw_awlen\(3 downto 0) <= s_axi_hpw_awlen(3 downto 0);
  \^s_axi_hpw_awsize\(2 downto 0) <= s_axi_hpw_awsize(2 downto 0);
  \^s_axi_hpw_awvalid\ <= s_axi_hpw_awvalid;
  \^s_axi_hpw_bready\ <= s_axi_hpw_bready;
  \^s_axi_hpw_wdata\(31 downto 0) <= s_axi_hpw_wdata(31 downto 0);
  \^s_axi_hpw_wlast\ <= s_axi_hpw_wlast;
  \^s_axi_hpw_wstrb\(3 downto 0) <= s_axi_hpw_wstrb(3 downto 0);
  \^s_axi_hpw_wvalid\ <= s_axi_hpw_wvalid;
  m_axi_hp_araddr(31 downto 0) <= \^s_axi_hpr_araddr\(31 downto 0);
  m_axi_hp_arburst(1 downto 0) <= \^s_axi_hpr_arburst\(1 downto 0);
  m_axi_hp_arlen(3 downto 0) <= \^s_axi_hpr_arlen\(3 downto 0);
  m_axi_hp_arsize(2 downto 0) <= \^s_axi_hpr_arsize\(2 downto 0);
  m_axi_hp_arvalid <= \^s_axi_hpr_arvalid\;
  m_axi_hp_awaddr(31 downto 0) <= \^s_axi_hpw_awaddr\(31 downto 0);
  m_axi_hp_awburst(1 downto 0) <= \^s_axi_hpw_awburst\(1 downto 0);
  m_axi_hp_awlen(3 downto 0) <= \^s_axi_hpw_awlen\(3 downto 0);
  m_axi_hp_awsize(2 downto 0) <= \^s_axi_hpw_awsize\(2 downto 0);
  m_axi_hp_awvalid <= \^s_axi_hpw_awvalid\;
  m_axi_hp_bready <= \^s_axi_hpw_bready\;
  m_axi_hp_rready <= \^s_axi_hpr_rready\;
  m_axi_hp_wdata(31 downto 0) <= \^s_axi_hpw_wdata\(31 downto 0);
  m_axi_hp_wlast <= \^s_axi_hpw_wlast\;
  m_axi_hp_wstrb(3 downto 0) <= \^s_axi_hpw_wstrb\(3 downto 0);
  m_axi_hp_wvalid <= \^s_axi_hpw_wvalid\;
  s_axi_hpr_arready <= \^m_axi_hp_arready\;
  s_axi_hpr_rdata(31 downto 0) <= \^m_axi_hp_rdata\(31 downto 0);
  s_axi_hpr_rlast <= \^m_axi_hp_rlast\;
  s_axi_hpr_rvalid <= \^m_axi_hp_rvalid\;
  s_axi_hpw_awready <= \^m_axi_hp_awready\;
  s_axi_hpw_bvalid <= \^m_axi_hp_bvalid\;
  s_axi_hpw_wready <= \^m_axi_hp_wready\;
end STRUCTURE;
